services:
  - type: web
    name: springboot-backend
    env: docker
    dockerfilePath: ./springboot-backend/ecom/Dockerfile
    repo: https://github.com/Prasad-Bhumkar/ecom-react-springboot.git
    branch: main # Replace with your branch name
    envVars:
      - key: DATABASE_URL
        value: your_external_database_url_here # REPLACE THIS IN RENDER DASHBOARD
    healthCheckPath: /actuator/health


